version: '3'
services:
  films:
    build:
      context: .
      dockerfile: films-api
    ports:
      - "8081:8081"

    networks:
      - net

  authorization:
    build:
      context: .
      dockerfile: authorization-api
    ports:
      - "8080:8080"
      - "50051:50051"

    networks:
      - net

networks:
  net:
    driver: bridge