version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
      - "50051:50051"
    depends_on:
      - redis
    networks:
      - net

networks:
  net:
    driver: bridge